### ISSUE TITLE
Aufgabe 1

### ISSUE THREAD

**Issue by Hasan222222** [alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt#1]
Ich hab gerade eben bei der ersten Aufgabe die verschiedenen Aufgabenbereiche zusammengefasst und hochgeladen (außer Teil d, darum kümmert sich Akin)

**Comment by alinaabro** [comment]
Ok, ich gucke mir mal den Code an ob alles so passt.

**Comment by alinaabro** [comment]
Hab mir den Code anguckt und gesehen, dass du die Anrede in 4 Kategorien eingeteilt hast und dass du die anderen Anreden diesen zugeteilt hast. Ich würde die entweder alle in eine andere Kategorie packen und die Sonstige nennen oder dass so lassen, aber dann sollten wir das gründlich dokumentieren.

**Comment by GRyzhkovskii** [comment]
Ich habe den Code für 1d) geschrieben.  Morgen setze ich den in unsere Hauptdatei ein.
