### ISSUE TITLE
README Datei

### ISSUE THREAD

**Issue by alinaabro** [alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt#11]
Habe jetzt die grobe Struktur für die Readme Datei angefertigt und schon bisschen was geschrieben.

**Comment by alinaabro** [comment]
Die readme Datei ist jetzt übrigens schon fertig, ihr könnt ja mal drüber gucken.

**Comment by Hasan222222** [comment]
Hab jetzt drüber geguckt und fand die Perfekt.
