### ISSUE TITLE
Fehlende Werte

### ISSUE THREAD

**Issue by alinaabro** [alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt#12]
Hab gerade gesehen das wir noch keine Funktion für Fehlende Werte haben. Könnte das vielleicht jemand schreibe und noch in den Code einfügen.

**Comment by Hasan222222** [comment]
Eigentlich kannst du die Summe der Fehlenden Werte so bestimmen: sum(is.na(daten$Age))

**Comment by alinaabro** [comment]
Ok, dann weiß ich bescheid.
