### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by alinaabro** [alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt#14]
Habe jetzt auch Links in die Sidebar des wikis gestellt, so dass man einfach drauf klicken kann und zu der jeweiligen Seite gebracht wird. Probiert mal aus ob das auch bei euch geht und macht dann die Dokumentation für Aufgabe 1 (die Personen die daran gearbeitet haben).

**Comment by Hasan222222** [comment]
Alles klar, danke 
Werde dann später die Dokumentation schreiben.

**Comment by KMarlinW** [comment]
Im Wiki unter den Ergebnissen müssten noch, wie abgesprochen, die Auffälligkeiten die die eigene Analysemethode aufzeigt beschrieben werden.
