### ISSUE TITLE
Aufgabe 2a) 

### ISSUE THREAD

**Issue by Hasan222222** [alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt#2]
Ich wollte gerade anfangen mit der Aufgabe 2a) und hab mir überlegt, dass die Funktion folgende Werte ausrechnen soll: 
- arithmetisches Mittel
- Median
- Standartabweichung 
- Varianz
-  Quantile
Denkt ihr es gibt noch andere wichtige Werte die ich ergänzen soll?

**Comment by AkMun47** [comment]
Ich würde noch die Lagemaße des Maximums bzw. Minimums ergänzen.

**Comment by Hasan222222** [comment]
Ja stimmt, gut das du mich dran erinnert hast

**Comment by Hasan222222** [comment]
Hab gerade eben den fertig Code für die 2a) hochgeladen.

**Comment by GRyzhkovskii** [comment]
Ich glaube wir sollen für die Aufgabe 2 weitere R-Skripte erstellen, wie in der Aufgabenstellung beschrieben ist. Ich habe die ursprungliche Datei "Wissenschaftliches Arbeiten.R" in 2 Teile geteilt und die entsprechend genannt. "Datensatzvorbereitung.R" enthält das Skript zum Aufgabe 1, und "Funktionen-R-Skript 1.R" enthält das Skript zum Aufgabe 2a.

**Comment by Hasan222222** [comment]
Alles klar, perfekt

**Comment by GRyzhkovskii** [comment]
Habe die zusätzliche Funktion in 2(vi) geschrieben, die Histograms von metrischen Merkmalen nach einem kategoriellen Merkmal plottet. Es sieht so aus:
![Beispiel 2vi](https://github.com/alinaabro/Wissenschaftliches-Arbeiten-GitHub-Projekt/assets/160510315/ce8d7c6d-7dcb-4cea-a943-ecc61717cc4c)
